### ISSUE TITLE
Should we use the wiki in this repo?

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/iGenCoders#2]
Hi guys,

I was thinking that the wiki (in the github repo) might be easier to use, than the markdown documents for this cause (maybe for some parts of the meetups as well, but that's a off-topic).

For instance it is match easier to have a wiki page with the links we have gathered and a short description for each one.  This way people involved can go directly on the wiki and add new links without the extra hustle of commit messages etc. It's now a huge difference, but it fills more suitable to me.

I also believe that wikis are easier navigated by external users (i.e. teachers and students).

What do you think?

**Comment by gsaslis** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1: Let's use the wiki and keep the repo cleaner for code and projects.

**Comment by daknob** [comment]
:+1: I created the home page. We can work our way from there with any resources we may discover, etc.
